# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '16.6'
  # Pods for iosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'MacosCLI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :osx, '13.5'
  
  # Pods for MacosCLI
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'TVosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :tvos, '16.6'
  
  # Pods for TVosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'WatchosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '9.6'
  
  # Pods for WatchosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'WatchosApp Watch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '9.6'
  
  # Pods for WatchosApp WatchKit App
  pod 'kotlin_library', :path => '../kotlin-library'
end
